name: icat
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- numpy
- python=3.10
- panel
- jupyter
- jupyterlab
- scikit-learn
- nodejs
- pandas
- ipyvuetify
- ipywidgets
- pytest
- pytest-mock
